# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit AI Code Review Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US
early_access: false

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # Files and patterns to ignore during review
  path_filters:
    - "!**/*.lock"
    - "!**/*.md"
    - "!**/docs/**"
    - "!**/examples/**"
    - "!**/.github/**"

  # Custom review instructions for GraphForge
  instructions:
    - Focus on correctness of openCypher semantics
    - Check for proper error handling and type safety
    - Verify test coverage for new features
    - Ensure docstrings are present for public APIs
    - Check for performance implications in query execution
    - Validate that changes maintain TCK compliance
    - Look for potential security issues (SQL injection patterns, etc.)
    - Verify backward compatibility for API changes
    - Prefer small, focused PRs (< 300 lines)
    - Flag any bandaid fixes or workarounds

chat:
  auto_reply: true
